language: rust

sudo: required

os:
  # - linux
  - osx

env:
  global:
    - CHEZSCHEMELIBDIRS="$TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR/thunderchez"
    - CHEZSCHEMELIBEXTS="ss:sls"
  
addons:
  homebrew:
    update: true
    packages:
      - chezscheme   
  apt:
    update: true
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev
      - uuid-dev

before_install:
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y chezscheme9.5 ; fi
  - petite --script "${TRAVIS_BUILD_DIR}/build.ss"

script:
  - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR petite --libdirs "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}/thunderchez" --script "${TRAVIS_BUILD_DIR}/tests.ss"