language: rust

sudo: required

os:
  - linux
  - osx

env:
  global:
    - CHEZSCHEMELIBDIRS="${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}/chez-finalize:${TRAVIS_BUILD_DIR}/thunderchez"
    - DEPLOY_FILE="chezure_`uname`_`uname -m`"
  
addons:
  homebrew:
    update: true
    packages:
      - aria2
      - ncurses
      - ossp-uuid
  apt:
    update: true
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev
      - uuid-dev
      - zlib1g-dev
      - aria2

before_install:  
  - /bin/bash -e ./.travis/install_chez
  - scheme --script "${TRAVIS_BUILD_DIR}/build.ss"

script:
  - scheme --script "${TRAVIS_BUILD_DIR}/tests.ss"

before_deploy:
  - rm -rf chezure/*
  - mv chezure.so chezure
  - mv librure.* chezure
  - zip -r $DEPLOY_FILE.zip chezure
  - tar czf $DEPLOY_FILE.tar.gz chezure

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - $DEPLOY_FILE.zip
    - $DEPLOY_FILE.tar.gz
  skip_cleanup: true
  # on:
    # tags: true
  draft: true
  overwrite: true
