language: rust

sudo: required

os:
  - linux
  - osx

env:
  global:
    - CHEZSCHEMELIBDIRS="${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}/thunderchez"
  
addons:
  homebrew:
    update: true
    packages:
      - chezscheme   
  apt:
    update: true
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev
      - uuid-dev
      - zlib1g-dev
      - aria2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /bin/bash -e ./.travis/install_chez ; fi
  - petite --script "${TRAVIS_BUILD_DIR}/build.ss"

script:
  - chez --script "${TRAVIS_BUILD_DIR}/tests.ss
  