language: rust

sudo: required

os:
  - linux
  - osx

env:
  global:
    - CHEZSCHEMELIBDIRS="${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}/thunderchez"
  
addons:
  homebrew:
    update: true
    packages:
      - aria2
      - ncurses
      - ossp-uuid
  apt:
    update: true
    packages:
      - libncurses5-dev
      - libgmp-dev
      - libffi-dev
      - uuid-dev
      - zlib1g-dev
      - aria2

before_install:
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /bin/bash -e ./.travis/install_chez ; fi
  - /bin/bash -e ./.travis/install_chez
  - petite --script "${TRAVIS_BUILD_DIR}/build.ss"

script:
  - scheme --script "${TRAVIS_BUILD_DIR}/tests.ss"
  # - mkdir build
  # - mv chezure.so ./build; mv librure.* ./build  
